### ISSUE TITLE
setup command (at least) doesn't work when cf-cli@8 is installed

### ISSUE THREAD

**Issue by rahearn** [cloud-gov/cg-manage-rds#11]
When cf-cli@8 is installed, cg-manage-rds crashes when retrieving credentials for the service key because the cli output changed format from version 7.

## Notes

- 8 has an extra "credentials" key that 7 does not have

## Acceptance Criteria

- [ ] `cg-manage-rds setup DB_NAME` outputs a connection string whether using cf-cli@7 or cf-cli@8.
- [x] OR `cg-manage-rds` only supports one or the other version, but outputs a warning message if an unexpected version is installed

**Comment by rbogle** [comment]
https://github.com/cloud-gov/cg-manage-rds/pull/13 addresses this issue
