### ISSUE TITLE
`invalid option` on restore during clone

### ISSUE THREAD

**Issue by bengerman13** [cloud-gov/cg-manage-rds#3]
```
Performing import to <redacted>
Importing to Postgres DB: <redacted>
Importing with:
    psql -d <redacted> -f db_backup.sql -O -c --if-exist
Processing.... Command Failed!
Error: psql: invalid option -- O
Try "psql --help" for more information.
```

**Comment by rbogle** [comment]
Got it. Option Defaults shouldnt apply when using the psql command vs the pg_restore command. Fixing.

**Comment by rbogle** [comment]
@bengerman13  new release -> updated brew formula 
You can do a `brew upgrade cg-manage-rds` to pick up the fix.

**Comment by rahearn** [comment]
I installed `cg-manage-rds` via homebrew (`brew install cloud-gov/cloudgov/cg-manage-rds`) today and hit this exact issue.

**Comment by rahearn** [comment]
It looks like the v0.2.0 release as tagged is somehow not a commit on any branch, and does not include the fix from #4.

<img width="2092" alt="Screen Shot 2022-09-21 at 10 05 19 AM" src="https://user-images.githubusercontent.com/285842/191526092-908003c7-09e4-4fcc-9705-50f598077633.png">

**Comment by rbogle** [comment]
Well thats very weird. Not sure how that happened...but pushed a new tag on the current commit. So the release to hombrew should have the current code.

**Comment by rahearn** [comment]
I had already deleted it, but can confirm that a new install from `homebrew` got 0.2.1 and was able to clone a db with extremely minimal data in it.

**Comment by rbogle** [comment]
@rahearn Thank you!!
