### ISSUE TITLE
Error in `cg-manage-rds import` from unexpected service key format 

### ISSUE THREAD

**Issue by nathanweeks** [cloud-gov/cg-manage-rds#6]
Current behavior observed with a6bcabc:
```
$ cg-manage-rds import -f my.sql my-mysql-rds-service
...
  File ".../cg_manage_rds/cmds/mysql.py", line 74, in credentials
    creds["local_port"] = int(creds.get("port")) + 30000
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```
Stepping through in a debugger & setting a breakpoint at that line, the (obfuscated) `creds` dict is:
```
(Pdb) p creds
{'credentials': {'db_name': '...', 'host': '..', 'name': '...', 'password': '...', 'port': '3306', 'uri': '...', 'username': '...'}} 
```

I worked around this by changing:
https://github.com/cloud-gov/cg-manage-rds/blob/a6bcabcf92ce4abe85e03d369686ac3de9cdfc63/cg_manage_rds/cmds/mysql.py#L73-L74

to:

```
        creds = cf.get_service_key(key_name, service_name)["credentials"]
        creds["local_port"] = int(creds.get("port")) + 30000
```

I suppose this would have to be done for psql.py as well.

Or perhaps dict returned by cg_manage_rds.cmds.cf_cmds.get_service_key() could be the value associated with the "credentials" key.

**Comment by rbogle** [comment]
this is interesting, thats not how credentials come through on my system. 
are you running on mac or linux?

**Comment by rbogle** [comment]
We will add support for v8 when we generallly support that on our platform. For now we check for v7

**Comment by nathanweeks** [comment]
Thanks! Is there an ETA for cf CLI v8 support (or a GitHub issue that can be subscribed to)?
